import assert from 'node:assert/strict'
import { test } from 'node:test'
import { z } from 'zod'
import { generateTypes } from './typegen.js'
import { manifestSchema } from './manifest.js'

const manifest = manifestSchema.parse({
  entities: [
    {
      prefix: 'contents',
      slug: 'posts',
      cardinality: 'many',
      kind: 'collection',
      fields: [
        { name: 'title', type: 'text', required: true, minLength: 1 },
        { name: 'summary', type: 'text' },
        { name: 'views', type: 'number', integer: true, defaultValue: 0 },
        { name: 'featured', type: 'boolean', defaultValue: false },
        { name: 'status', type: 'select', options: ['draft', 'published'], required: true },
        { name: 'publishedAt', type: 'date' },
        { name: 'authors', type: 'relationship', to: 'users', many: true },
        { name: 'tags', type: 'taxonomy', to: 'tags', many: true },
        { name: 'hero', type: 'media' },
        { name: 'seo', type: 'group', fields: [{ name: 'metaTitle', type: 'text' }] },
        { name: 'blocks', type: 'array', fields: [{ name: 'heading', type: 'text', required: true }] },
        { name: 'weird key', type: 'text' },
        { name: 'customThing', type: 'blocks' },
      ],
    },
    {
      prefix: 'site',
      slug: 'settings',
      cardinality: 'single',
      timestamps: false,
      fields: [{ name: 'siteName', type: 'text', required: true }],
    },
  ],
})

test('generateTypes mirrors buildDocumentSchema field-by-field', () => {
  const out = generateTypes(manifest)

  assert.match(out, /export const postsSchema = z\.object\(\{/)
  assert.match(out, /export type Posts = z\.infer<typeof postsSchema>/)
  assert.match(out, /id: z\.string\(\),/)
  // required + constraint, no optional wrapping
  assert.match(out, /title: z\.string\(\)\.min\(1\),/)
  // not required -> nullable().optional()
  assert.match(out, /summary: z\.string\(\)\.nullable\(\)\.optional\(\),/)
  // default wins over optional
  assert.match(out, /views: z\.number\(\)\.int\(\)\.default\(0\),/)
  assert.match(out, /featured: z\.boolean\(\)\.default\(false\),/)
  // required enum
  assert.match(out, /status: z\.enum\(\["draft", "published"\]\),/)
  assert.match(out, /publishedAt: z\.coerce\.date\(\)\.nullable\(\)\.optional\(\),/)
  assert.match(out, /authors: z\.array\(z\.string\(\)\)\.nullable\(\)\.optional\(\),/)
  assert.match(out, /tags: z\.array\(z\.string\(\)\)\.nullable\(\)\.optional\(\),/)
  assert.match(out, /hero: z\.string\(\)\.nullable\(\)\.optional\(\),/)
  // group -> nested object
  assert.match(out, /seo: z\.object\(\{/)
  assert.match(out, /metaTitle: z\.string\(\)\.nullable\(\)\.optional\(\),/)
  // array -> array of object
  assert.match(out, /blocks: z\.array\(z\.object\(\{/)
  assert.match(out, /heading: z\.string\(\),/)
  // quoted invalid identifier
  assert.match(out, /"weird key": z\.string\(\)\.nullable\(\)\.optional\(\),/)
  // unknown/module field type falls back to z.unknown()
  assert.match(out, /customThing: z\.unknown\(\)\.nullable\(\)\.optional\(\),/)
  // timestamps included for posts, excluded for settings
  assert.match(out, /createdAt: z\.string\(\),/)
  assert.doesNotMatch(out.split('settingsSchema')[1] ?? '', /createdAt/)
  // delivery-path map keys
  assert.match(out, /"contents\/posts": postsSchema,/)
  assert.match(out, /"site\/settings": settingsSchema,/)
  assert.match(out, /Generated by `kon10 typegen`/)
})

/** Strip TS-only syntax so the generated schema source can run under `new Function`. */
function toRunnable(src: string): string {
  return src
    .split('\n')
    .filter((l) => !l.startsWith('import ') && !l.startsWith('export type ') && !l.startsWith('//') && !l.startsWith('/* eslint'))
    .map((l) => (l.startsWith('export ') ? l.slice('export '.length) : l))
    .join('\n')
    .replace(/ as const/g, '')
}

test('the emitted schemas validate and coerce like the server', () => {
  const runnable = toRunnable(generateTypes(manifest))
  const factory = new Function('z', `${runnable}\nreturn entities;`) as (
    zod: typeof z,
  ) => Record<string, z.ZodType>
  const entities = factory(z)

  const postSchema = entities['contents/posts']!
  const parsed = postSchema.parse({
    id: '1',
    title: 'Hello',
    status: 'published',
    publishedAt: '2024-01-02T00:00:00.000Z',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  }) as Record<string, unknown>

  // defaults applied, date coerced, optionals absent are fine
  assert.equal(parsed.views, 0)
  assert.equal(parsed.featured, false)
  assert.ok(parsed.publishedAt instanceof Date)

  // required field missing -> rejected
  assert.equal(postSchema.safeParse({ id: '1', status: 'published', createdAt: 'x', updatedAt: 'y' }).success, false)
  // enum value outside the set -> rejected
  assert.equal(
    postSchema.safeParse({ id: '1', title: 'x', status: 'nope', createdAt: 'a', updatedAt: 'b' }).success,
    false,
  )
})
